name: CI/CD

# Dispara em todo push na main
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test with Maven
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código
      - uses: actions/checkout@v3

      # 2. Configura Java 17 e cache de dependências
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Compila e empacota
      - name: Build package
        run: mvn clean package -B

      # 4. Roda os testes
      - name: Run tests
        run: mvn test -B

  deploy:
    name: Trigger Render Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      # 5. Dispara o webhook para o Render redeployar
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
